//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 Rancher Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NavLink) DeepCopyInto(out *NavLink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NavLink.
func (in *NavLink) DeepCopy() *NavLink {
	if in == nil {
		return nil
	}
	out := new(NavLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NavLink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NavLinkList) DeepCopyInto(out *NavLinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NavLink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NavLinkList.
func (in *NavLinkList) DeepCopy() *NavLinkList {
	if in == nil {
		return nil
	}
	out := new(NavLinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NavLinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NavLinkSpec) DeepCopyInto(out *NavLinkSpec) {
	*out = *in
	if in.ToService != nil {
		in, out := &in.ToService, &out.ToService
		*out = new(NavLinkTargetService)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NavLinkSpec.
func (in *NavLinkSpec) DeepCopy() *NavLinkSpec {
	if in == nil {
		return nil
	}
	out := new(NavLinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NavLinkTargetService) DeepCopyInto(out *NavLinkTargetService) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(intstr.IntOrString)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NavLinkTargetService.
func (in *NavLinkTargetService) DeepCopy() *NavLinkTargetService {
	if in == nil {
		return nil
	}
	out := new(NavLinkTargetService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyEndpoint) DeepCopyInto(out *ProxyEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyEndpoint.
func (in *ProxyEndpoint) DeepCopy() *ProxyEndpoint {
	if in == nil {
		return nil
	}
	out := new(ProxyEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxyEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyEndpointBodyRule) DeepCopyInto(out *ProxyEndpointBodyRule) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyEndpointBodyRule.
func (in *ProxyEndpointBodyRule) DeepCopy() *ProxyEndpointBodyRule {
	if in == nil {
		return nil
	}
	out := new(ProxyEndpointBodyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyEndpointCredentialType) DeepCopyInto(out *ProxyEndpointCredentialType) {
	*out = *in
	if in.RequiredFields != nil {
		in, out := &in.RequiredFields, &out.RequiredFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyEndpointCredentialType.
func (in *ProxyEndpointCredentialType) DeepCopy() *ProxyEndpointCredentialType {
	if in == nil {
		return nil
	}
	out := new(ProxyEndpointCredentialType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyEndpointInjectionDetails) DeepCopyInto(out *ProxyEndpointInjectionDetails) {
	*out = *in
	if in.AllowedHeaders != nil {
		in, out := &in.AllowedHeaders, &out.AllowedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BodyInjectionRules != nil {
		in, out := &in.BodyInjectionRules, &out.BodyInjectionRules
		*out = make([]ProxyEndpointBodyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyEndpointInjectionDetails.
func (in *ProxyEndpointInjectionDetails) DeepCopy() *ProxyEndpointInjectionDetails {
	if in == nil {
		return nil
	}
	out := new(ProxyEndpointInjectionDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyEndpointList) DeepCopyInto(out *ProxyEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxyEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyEndpointList.
func (in *ProxyEndpointList) DeepCopy() *ProxyEndpointList {
	if in == nil {
		return nil
	}
	out := new(ProxyEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxyEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyEndpointSpec) DeepCopyInto(out *ProxyEndpointSpec) {
	*out = *in
	if in.AllowedCredentials != nil {
		in, out := &in.AllowedCredentials, &out.AllowedCredentials
		*out = make([]ProxyEndpointCredentialType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.InjectionDetails.DeepCopyInto(&out.InjectionDetails)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyEndpointSpec.
func (in *ProxyEndpointSpec) DeepCopy() *ProxyEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyEndpointSpec)
	in.DeepCopyInto(out)
	return out
}
